app:
  version: "@project.version@"
  build:
    timestamp: "@maven.build.timestamp@"

server:
  port: 8080

spring:
  application:
    name: "@project.artifactId@"
    description: "@project.description@"

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  metrics:
    export:
      otlp:
        endpoint: http://otel-collector.observability.svc.cluster.local:4318/v1/metrics
        protocol: http/protobuf
        enabled: true
    tags:
      application: notificacao-service
      service: ms-notificacao
    distribution:
      percentiles-histograms: true
      minimum-expected-value:
        http.server.requests: 1ms
      maximum-expected-value:
        http.server.requests: 30s
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
